START TRANSACTION;

DROP SCHEMA api CASCADE;

DROP SCHEMA auth CASCADE;

DROP SCHEMA "data" CASCADE;

DROP SCHEMA pgjwt CASCADE;

DROP SCHEMA rabbitmq CASCADE;

DROP SCHEMA request CASCADE;

DROP SCHEMA settings CASCADE;

DROP EXTENSION plpgsql CASCADE;

DROP EXTENSION pgcrypto CASCADE;

DROP TYPE _time_trial_type;

DROP ROLE IF EXISTS anonymous, api, webuser;

COMMIT TRANSACTION;
